edex_container:
  variable_spec: Sectorized_CMI
  rx_port: 6002
  tx_port: 6001
  rx_port_trigger: 6000
  tx_port_trigger: 7000
  host: edexc
  pygcdm_client: edexc
  pygcdm_server: processc

process_container:
  variable_spec: Sectorized_CMI
  rx_port: 6001
  tx_port: 6002
  rx_port_trigger: 7000
  tx_port_trigger: 6000
  host: processc
  pygcdm_client: processc
  pygcdm_server: edexc
