version: "3"
services:
  processc:
    container_name: processc
    build:
      context: .
      dockerfile: ./processc/Dockerfile
    tty: true
    networks: 
      - pygcdm-net
    command: python server/edex_container_server.py process_container

  edex:
    container_name: edexc
    build:
      context: .
      dockerfile: ./edexc/Dockerfile
    privileged: true
    ports:
      - 9581:9581
      - 9582:9582
      - 388:388
    tty: true
    networks: 
      - pygcdm-net
    command: ["/usr/sbin/init"]

networks:
  pygcdm-net:
    name: pygcdm-net

