version: "3"
services:
  tf:
    container_name: tfc
    build:
      context: .
      dockerfile: ./tfc/Dockerfile
    tty: true
    # ports only used for external access not on pygcdm-net
    ports:
      - 8500:8500
      - 8501:8501
    networks: 
      - pygcdm-net

  process:
    container_name: processc
    build:
      context: .
      dockerfile: ./processc/Dockerfile
    tty: true
    networks: 
      - pygcdm-net
    command: python server/container_servers.py process_container

  edex:
    container_name: edexc
    build:
      context: .
      dockerfile: ./edexc/Dockerfile
    privileged: true
    ports:
      - 9581:9581
      - 9582:9582
      - 388:388
    tty: true
    networks: 
      - pygcdm-net
    command: ["/usr/sbin/init"]

networks:
  pygcdm-net:
    name: pygcdm-net

