version: "3"
services:
  tf:
    container_name: tfc
    build: .
    tty: true
    networks: 
      - pygcdm-net
    command: bash -c "python edex_container_server.py tf_container"

  edex:
    container_name: edexc
    build: .
    tty: true
    networks: 
      - pygcdm-net
    command: bash -c "python edex_container_server.py edex_container"
networks:
  pygcdm-net:
    name: pygcdm-net

