version: "3"
services:
  tf:
    container_name: tfc
    build:
      context: .
      dockerfile: ./tfc/Dockerfile
    tty: true
    networks: 
      - awipsml-net
    command: tensorflow_model_server  --port=8500 --rest_api_port=8501  --model_name=model --model_base_path=/models/model

  process:
    container_name: processc
    build:
      context: .
      dockerfile: ./processc/Dockerfile
    tty: true
    networks: 
      - awipsml-net
    command: python server/container_servers.py process_container

  edex:
    container_name: edexc
    build:
      context: .
      dockerfile: ./edexc/Dockerfile
    privileged: true
    # these ports need to be exposed outside of awipsml-net for upstream LDM and CAVE
    ports:
      - 9581:9581
      - 9582:9582
      - 388:388
    tty: true
    networks: 
      - awipsml-net
    command: /usr/sbin/init

networks:
  awipsml-net:
    name: awipsml-net

