version: "3"
services:
  tf:
    container_name: tfc
    build:
      context: .
      dockerfile: ./tfc/Dockerfile
    tty: true
    networks: 
      - pygcdm-net
    command: python edex_container_server.py tf_container

  edex:
    container_name: edexc
    build:
      context: .
      dockerfile: ./edexc/Dockerfile
    privileged: true
    ports:
      - 9581:9581
      - 9582:9582
      - 388:388
    tty: true
    networks: 
      - pygcdm-net
    command: ["/usr/sbin/init"]

networks:
  pygcdm-net:
    name: pygcdm-net

