edex_container:
  rx_port: 6002
  tx_port: 6001
  rx_port_trigger: 6000
  host: edexc
  pygcdm_client: edexc
  pygcdm_server: tfc

tf_container:
  rx_port: 6001
  tx_port: 6002
  rx_port_trigger: 7000
  host: tfc
  pygcdm_client: tfc
  pygcdm_server: edexc
