edex_container:
  variable_spec: Sectorized_CMI
  rx_port: 6002
  tx_port: 6001
  rx_port_trigger: 6000
  tx_port_trigger: 7000
  host: localhost
  pygcdm_client: localhost
  pygcdm_server: localhost

process_container:
  variable_spec: Sectorized_CMI
  rx_port: 6001
  tx_port: 6002
  rx_port_trigger: 7000
  tx_port_trigger: 6000
  host: localhost
  pygcdm_client: localhost
  pygcdm_server: localhost
